/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    AppHeader: typeof import('./components/layout/AppHeader.vue')['default']
    AppLayout: typeof import('./components/layout/AppLayout.vue')['default']
    AppSidebar: typeof import('./components/layout/AppSidebar.vue')['default']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ATable: typeof import('ant-design-vue/es')['Table']
    ChatInput: typeof import('./components/chat/ChatInput.vue')['default']
    CitationCard: typeof import('./components/chat/CitationCard.vue')['default']
    MessageBubble: typeof import('./components/chat/MessageBubble.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SessionList: typeof import('./components/chat/SessionList.vue')['default']
    StatusBadge: typeof import('./components/document/StatusBadge.vue')['default']
    UploadZone: typeof import('./components/document/UploadZone.vue')['default']
  }
}
